# Generated by Django 3.1.7 on 2021-02-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('linguagem', models.CharField(max_length=100, verbose_name='Linguagem')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
        ),
    ]
