# Generated by Django 3.2.8 on 2021-10-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_audit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audit',
            name='user',
        ),
        migrations.AddField(
            model_name='audit',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
